### ISSUE TITLE
关于训练成本

### ISSUE THREAD

**Issue by rookiebird** [s-JoL/Open-Llama#10]
你好，对于你描述的复现这个open-llma的训练成本比较好奇，因为之前的你在示例图片底下说复现这样一个模型大概是2W刀，但是到高性能部分变成了9w刀，不太确定具体价格？ 

还有就是想再请教下训练所需显存？ 如果不考虑时间， 4卡a100 * 80g 能复现这个结果吗？

**Comment by s-JoL** [comment]
抱歉，这个确实是我没写清楚。这两个不一致实际是训练用的数据量不一致导致的。
2W是按110B token估计，9w是按500B token估计的。
readme里前三张图是在110B token的结果，下面的对轮对话是用了300B数据训练出来的（当然这不是说预训练多了才能多轮对话，这个主要还是instruct-tuning数据带来的，用110B我相信也可以）。

从Loss来看在110B和300B时下降已经很不明显了，从下面图也可以看出。
![image](https://user-images.githubusercontent.com/16948304/231652633-733263df-3438-4204-be35-9fd1ee9c62b3.png)

现在给出的demo是300B token的模型，总共gpu时为31360，按这个估计需要49392美元。

如果不考虑时间， 4卡a100 * 80g 也可以，我刚才试了一下可以把batch size减小一点或者打开activation checkpoint都是可行的，同时可能要加很大的梯度累积，因为我不确定batch size有多大影响。但是如果要从头预训练确实需要很长时间，基于比如Llama的ckpt加入中文继续预训练可能是一个更好的方式。

这个我还没完全测试好，你可以看dev分支，在utils里提供了基于llama tokenizer加中文以及把原始的ckpt修改为适配的格式，然后在pretrain_config.yaml里加修改后的ckpt地址可以实现加载llama原本的参数继续训练。我跑了几千step 看起来loss确实可以正常下降。

**Comment by rookiebird** [comment]
好的，谢谢大佬持续关注中
