### ISSUE TITLE
Help! Lots of skippings in running dataset/train-tokenizer.py

### ISSUE THREAD

**Issue by mikeda100** [s-JoL/Open-Llama#12]
How to solve this problem?
Thanks a lot!

----------------------------------------------------------

Loading data from data/pretrain_data/part-wudao-3029.jsonl.zst
trainer_interface.cc(367) LOG(INFO) Reserved chars are found. Skipped: 月建
月建，一般是指十二支而言，如建子、建丑、建寅等等。“建”代表北斗七星斗柄顶端的指向。古老天文学称北斗星斗柄所指为“建”，干支历将一岁划分为十二辰，斗柄旋转而依次指为十二辰（十二月令），称为“十二月建”。十二月建是依据二十四节气而来的节气月。 [1-2] 此外，建又指十二个表示当下态势的字，即''建，除，满，平，定，执，破，危，成，收，开，闭”，月建指摇卦当月的月地支，也称月令、月将。月建在当月三十日中当权得令，对卦爻的旺衰有着直接影响。五行在四季十二月中呈旺相休囚的周期性变化，当令的月地支便为月建。概念 概念一：“月建”，又称月令，简称节，是古人干支纪月的一种方法。“建”代表北斗七星斗柄顶端的指向，是干支历法中十二个月之始。古代天文学称北斗星斗柄所指为建，一岁之中斗柄旋转而依次指为十二辰，称为“十二月建”。十二月建即：一月建寅，二月建卯，三月建辰，四月建巳，五月建午，六月建未，七月建申，八月建酉，九月建戌，十月建亥，十一月建子，十二月建丑。 [2-4] 概念二：月建是指十二个表示当下态势的字，即''建，除，满，平，定，执，破，危，成，收，开，闭”。月建指摇卦当月的月地支，也称月令、月将。月建在当月三十日中当权得令，对卦爻的旺衰有着直接影响。五行在四季十二月中呈旺相休囚的周期性变化，当令的月地支便为月建。 释义 《汉书.律历志》：“辰者，日月之会而建所指也。”就说明了辰，月建所指。《易·系辞》：寒暑相推而岁成。古人以“岁”来表示寒暑交替。岁，“岁”又名为“摄提”、“太岁”，是天皇氏时代创制的纪元星名。《盘古王表》：“天皇氏始制干支之名，以定岁之所在”。《三皇本纪》：“天皇氏，木德王，岁起摄提”。《太平御览》卷17引《释名》曰：“岁，越也。越，故限也，年进也，进而前也，祀巳也，新气生，故气巳也，载载生物也。”《开元占经》卷67引《淮南鸿烈间诂》曰：“斗杓为小岁。（注：）岁之言越历十二辰而行。”古老天文学称北斗星斗柄所指为“建”。斗柄旋转一圈（从立春到下一立春），谓之一十二月建，“十二月建”是干支历法的基本内容，依据北斗星斗柄的指向确定。以北斗星斗柄所指的方位作为确定月份的标准，称为“斗建”，“建”代表北斗七星斗柄顶端的指向。北斗星斗柄绕东、南、西、北旋转一圈谓之一岁（摄提），干支历法将一岁划分为十二辰（或“十二月令”），每月令含两个节气，斗柄旋转而依次指向“十二辰”，称为“十二月建”。十二月建亦即是十二个节气月。 古人的所谓“月建”，就是把一年十二个月和天上的十二辰联系起来。十二辰是古代天文学的一个概念，就是把黄道（即太阳一年在天空中移动一圈的路线）附近的一周天十二等分，由东向西配以子，丑，寅，卯，辰，巳，午，未，申，酉，戌，亥十二支。十二支和十二月相配，依序称为建子月，建丑月，建寅月等等，这就叫“月建”。那么十二月份是怎样确定的呢？这个问题与太阳的周年视运动引起的北斗星转动有关。北斗星是大熊星座的七颗明亮的星，分布成斗形，因此中国古代称为北斗星。天枢，天璇（xuan音旋），天玑（ji音机），天权组成斗身。玉衡，开阳，摇光三星组成斗柄，古曰杓（biao音彪）。用直线把天璇，天枢两星连接起来向斗口方向延长约五倍的距离就遇到小熊座a星，即北极星。 北极星是出现在天空北部的一颗亮星，距地球北极很近，差不多正对着地轴，从地球上看，它的位置几乎不变。航海和旅行的人常靠它来辨别方向。因为北斗星围绕北极星转动，因次北斗星亦用来辨方向，定季节。人们可以根据初昏时北斗星斗柄所指的方向来决定季节：斗柄指东，天下皆春；斗柄指南，天下皆夏；斗柄指西，天下皆秋；斗柄指北，天下皆冬。同样，也可以根据北斗星斗柄所指十二辰中的不同位置来确定十二月份。以日南至（即冬至）所在之朔望月的日月相会日（朔日），北斗斗柄指辰位为“子”位，为建子月；日月之会日的斗柄所指“丑”位，为建丑月；日月之会日的斗柄所指“寅”，为建寅月。依此类推，日月之会日的斗柄所指十二辰中的那一支，就是建该支月，称为“月建”。然而随着时间的流逝，据说古人发现北斗星逐渐偏离原来的位置，于是改用赤道上直接定的十二支。 一般所谓月建是指十二支而言，如建子、建丑、建寅等等。有人认为月建是指（农历）月的大小而言，所以有大建和小建的谬论。 [1] 所谓“正月建寅”，其实是农历的正月（初一或朔）从天象中的寅位开始向卯排列。农历是一种阴阳历，采用加设闰月调整，闰月使用上月月建，其原因就是在闰月的朔日所指的辰位与上月相同。 在古代，月建对判断占事至关重要。 月建即月令，掌一月之权，可三旬之令，一月三十日当权得令，掌管万物之提纲，巡察六爻之善恶，操生杀之权柄。月建能助卦爻之衰弱，挫爻象之旺强，制服动变之爻，扶起飞伏之神。月建当权为主帅纲领，爻之衰弱者，能生之合之，拱之扶之，衰而亦旺。爻之强旺者，能克之冲之，刑之破之，旺而亦衰，卦有变爻克制动爻者，月建能制服变爻，卦有动爻克制静爻者，月建能制服动爻。用神伏藏，飞神压住者，月建能冲克飞神，扶助伏神而为用。 爻之月合而有用，爻逢月破而无功。月建合爻，则为月合而有用；月冲之爻，即为月破无用之爻。 月建不入爻，亦为有用；月建一入爻，愈见刚强。卦无用神，即以月建为用神，不必寻伏神。月建入卦动而作原神者，为福更大。动而作忌神者，为祸更凶。不入卦者，缓之；入卦者，速之。 在卦象中凡有卦爻地支与月地支相同，称为临月建。与月地支同类，称为临月扶。与月地支相冲，称为临月破。月建生卦爻，称为临月生，月建克卦爻，称为临月克。 徐墨斋师傅为他人占卦，如图：摇卦月是寅月,卦中父母爻（初九爻）为临月扶，妻财爻（九五爻）为临月破,兄弟爻（九四爻）为临月生,子孙丑土（六二爻）和子孙戌土（上九爻）为临月克，若卦爻地支中有寅木的，就为临月建。 例：寅月庚戌日，测求财得大有卦， 乾宫：火天大有（归魂） 六神 【本 卦】 螣蛇 ▅▅▅▅▅ 官鬼己巳火 应 勾陈 ▅▅ ▅▅ 父母己未土 朱雀 ▅▅▅▅▅ 兄弟己酉金 青龙 ▅▅▅▅▅ 父母甲辰土 世 玄武 ▅▅▅▅▅ 妻财甲寅木 白虎 ▅▅▅▅▅ 子孙甲子水 财爻寅木为用，临月建，而克世必得，但本旬为空，要到甲寅旬中，寅爻出空可得，果于甲寅日得财。 寓意 月建干支，利于用神为善。 月建干支，不利于用神为恶。 月建干支，利于用神，但为局中他神克运河或合住，善而不善，然亦不恶，平庸而已。 月建干支，不利于用神，但为局中他神克去或合住，恶而不恶，然亦不善，平庸而已。 应用 月建与流年 月建善，流年亦善，则更妙。 月建善，流年恶。则善中有恶。 月建恶，流年亦恶，则更恶。 月建恶，流年善，则恶中有善。 月建善，惟被局中某神克合，若流年制住克合之神，则仍佳妙。 月建恶，惟被局中某神克合，若流年制住克合之神，则仍蹇劣。 月建善，惟被局中某神克合，若流年生辅克合之神，则凶多吉少。 月建恶，惟被局中某神克合，若流年生辅克合之神，则吉多凶少。 月建善，流年再生助之，则更善。 月建恶，流年再生助之，则更恶 月建善，流年若克挫之，则善力减轻。 月建恶，流年若克挫之，则恶力减轻。 月建之干支 月建看法，月干重于月支，因干流动，而支固定。月建即流月也。或以干为上半月，支为下半月，不甚可信，总宜干支合看。亦有以月支所藏人元，分何者当旺几天，而定几天吉凶，更不足信，盖完全偏重于月支。成如此说，则月建可无须月干矣。智德师傅提醒，看命中强弱，且不能以建中人元旺几天而标定，况流年中之流动月建耶。 月建与时令 在干支历里：正月为寅，二月为卯，三月为辰，四月为巳，五月为午，六月为未，七月为申，八月为酉，九月为戌，十月为亥，十一月为子，十二月为丑；月支固定，故不若月干之重视。然而时令与月建，颇有关系焉。特叙述如后。 （一）春令木旺，甲寅月、乙卯月、甲辰月，则木更盛。丙寅月、丁卯月、丙辰月，则火得木生而亦强。戊寅月、己卯月、戊辰月，则土被木克而不健。庚寅月、辛卯月、庚辰月，则金为木挫而无力。壬寅月、癸卯月、壬辰月，则水受木泄亦疲弱。 （二）夏令火旺。丁巳月、丙午月、丁未月，则火更盛。己巳月、戊午月、己未月，则土得火生而亦强。辛巳月、庚午月、辛未月，则金被火熔而不健。癸巳月、壬午月、癸未月，则水为火灼而无力。乙巳月、甲午月、乙未月则木受火泄亦疲弱。 （三）秋令金旺。庚申月、辛酉月、庚戌月，则金更盛。壬申月、癸酉月、壬戌月，则水得金生而亦强。甲申月、乙酉月、甲戌月，则木被金克而不健。丙申月、丁酉月、丙戌月，则火为金磨而无力。戊申月、己酉月、戊戌月土受金泄亦疲弱。 （四）冬令水旺，癸亥月、壬子月、癸丑月，则水更盛。乙亥月，甲子月，乙丑月，则木得水生而亦强。丁亥月、丙子月、丁丑月，则火被水克而不健。己亥月、戊子月、己丑月，则土因水泛而无力。辛亥月、庚子月、辛丑月，则金受水泄亦疲弱。 （五）四立前各十八天土旺。戊辰月、己未月、戊戌月、己丑月，则土更甚。庚辰月、辛未月、庚戌月、辛丑月，则金得土生而亦强。壬辰月、癸未月、壬戌月、癸丑月，则水被土克而不健。甲辰月、乙未月、甲戌月、乙丑月，则木为土折而无力。丙辰月、丁未月、丙戌月、丁丑月，则火受土泄亦疲弱。
Loading data from data/pretrain_data/part-wudao-7.jsonl.zst
trainer_interface.cc(367) LOG(INFO) Reserved chars are found. Skipped: 问测2016年运
男、1982年农历11月生,在一家民营企业上班。 预测2016年:1、事业工作情况,工作上能否有机会转提升,自己投资的茶楼、培训学校是 否都有很大的发展,财利如何 2、现在有一个喜欢的人,出现了矛盾没有继续,是否可以修复,是否会遇到 合适的人结婚, 3、2016年文运如何,参加比赛可以获奖吗。 公历起卦时间:2016年1月8日16时18分 (手工指定)农历:乙未年十一月廿九日申时小寒:2016年01月06日06时47分立春: 2016年02月04日18时00分干支: 乙未年 己丑月 己丑日 壬申时 (日空:午未)神煞:驿马-亥 桃花-午 日禄-午 贵人-子,申 乾宫:风地观 离宫:风水涣 六神 伏神 本 卦 变 卦 勾陈 妻财辛卯木 ▅▅▅▅▅ 妻财辛卯木 ▅▅▅▅▅ 朱雀 兄弟壬申金 官鬼辛巳火 ▅▅▅▅▅ 官鬼辛巳火 ▅▅▅▅▅ 世 青龙 父母辛未土 ▅▅ ▅▅ 世 父母辛未土 ▅▅ ▅▅ 玄武 妻财乙卯木 ▅▅ ▅▅ 官鬼戊午火 ▅▅ ▅▅ 白虎 官鬼乙巳火 ▅▅ ▅▅ ╳→ 父母戊辰土 ▅▅▅▅▅ 应腾蛇 子孙甲子父母乙未土 ▅▅ ▅▅ 应 妻财戊寅木 ▅▅ ▅▅ 目前工作上平静,死水一潭,不下不上,你也没怎么跳槽的心思,就是有想法也不会真正付诸行动,难得找也懒得找茶馆经营总体顺当,指15年及16年都基本上差不多了情况,16年春、夏冬季生意比较好些,秋季惨淡一些。世父为书面作品:并到应爻顾客那里,卖画方面还行,不过每幅价位都不算高。16年应买家要求画、写的那种比较多,也容易成交。没有显示会有经营方式的大改变,维持目前形式,就可有稳定额度的收益。子爻不上卦又克弱,16年招生学员比15年少,还有中途退出的,教学生方面人数比15年减少起码近3成妻克世,处的那个女友关键她心不定,也可以说不够爱你吧,2人性格也存在某些本质差异不合,所以没看到能发展到真正在一起。 正2月矛盾多摩擦多,或会结束交往或决定放弃巳官动生世,单位农4、5月有一次提拨一批人之象,但巳化辰乃真兄爻竞争者,最终另外的同事抢得名额,世爻空,你会落空。在家中之西南方摆放一只瓷羊工艺品,上半年多穿红色系衣物,有争取助运之效流月大概运,农历月份为准正月体质偏差,防感冒及肠胃病,与女友别扭不少。二月与正月以上延续之外,财上赚得多花的也快,存不下来多少。卯妻动化官,女友或会提出分开、与你结束交往之类,并且另有考虑的人三月平平,无大喜亦无忧,与人合作事宜遇到某些问题难以达成一致四、五月单位开始研究提拔一批人,领导或会跟你透点风,勉励之意,但是泛泛之举,你也没多大竞争的劲头,自己生意上事宜正忙活中六月劳心劳神,工作、生意、教学、书画都会比较忙乱事多。
trainer_interface.cc(367) LOG(INFO) Reserved chars are found. Skipped: 杭州下城区治疗溢脂性脱发医院
杭州下城区治疗溢脂性脱发医院【杭州脱发医院-杭州植发医院】▃▅▆▇杭州杭城植发医院▇▆▅▃【24小时免费咨询杭城植发专家专业指导】 许多患者在面临脱发严重之后感到自卑、焦虑和烦恼,导致自信下降和社交孤独感,害怕引起他人的注意,对他人有敌对情绪,对人际关系过度敏感,长期的精神压抑令患者产生"社交危机感",对社会活动产生焦虑、畏惧的心理.当您 面临这样的困境时,考虑一下到一家好的植发医院做植发手术来破解这样的困境吧。 人们常说烦恼三千丝,而现在愈加多的人脱掉了这三千丝,却还是有数不清的烦恼。那么当有人正在遭遇或者将要遭遇 掉发的困扰时,我们应该怎样护理头发呢？ 不要用脱脂性强或碱性洗发剂 这类洗发剂的脱脂性和脱水太强,易使头发干燥、头皮坏死。应选用对头皮和头发无刺激 性的天然洗发剂,或根据自己的发质选用。最好不要一直使用某种洗发剂。 目前,杭州杭城植发医院植拥有三位在国内享有盛誉的植发专家。 陈海涛。杭州杭城医院植发科主任,国内著名植 发专家,fue中国第一人,杭城lhs高端技术的研发者。李长恒 。技术顾问,原上海华山皮肤科主任、学科带头人,上海皮肤科诊疗界的泰斗,国务院特殊津贴教授,皮肤病 国家科技进步二等奖获得者,杭城lhs高端技术的研发者。诸慕兰。特邀专家,杭州第三人民医院专家,杭城lhs高端技术的研发者,国务院特殊津贴教授。这三位专家在植发领域拥有多年的治疗脱发成功经验。做到贴心为您服务！ 近些年来,植发技术的不断成熟,让越来越多的脱发患者对植发有所了解。植发进入中国已经数十年,从传统植发技术逐渐发展到现在的第三代fue无痕植发技术,已经慢慢被脱发患者所认可。如今,大多数脱发患者都会选择通过植发技术来彻底治疗自己的脱发 问题。 那么,头发种植真的能解决脱发的问题吗？相信这是所以脱发患者在选择头发种植前最多的疑问。这里我们请到杭州杭城植发医院从事多年临床经验的专家为我们解答。头发种植真的能解决脱发问题吗？点击直接咨询 头发种植治疗脱发的原理 专家指出:头发种植亦属于自体毛发种植的一种,是通过运用显微外科手术,从人体后枕部提取部分健康的毛囊单位,经过特殊的分离、活化后按照脱发患者原本毛发生长的方向种植到脱发区域。待种植后的毛囊存活后便能长出新的头发来。 后枕部的头发提取后,会有影响吗？ 因为种植的毛囊单位来自于人体后枕部的毛囊,所以很多脱发患者会担心后枕部的毛囊提取后不就变的少了吗？这样不就影响到后枕部的头发密度了吗？针对这一问题,专家解释:医学研究表明,人体后枕部的毛囊组织不受雄性激素及外界的影响永不坏死,且后枕 部的头发密度是整体头发密度的2到4倍。所以,头发种植才会提取这部分的毛囊,且不会影响供体区(后枕部)头发的密度。 头发种植后能达到好的效果吗？ 专家介绍:现在的头发种植技术已经到了很成熟的地步,也是医学界公认的唯一有效治疗脱发问题的方法。因提取的后枕部的毛囊具有永不脱落的特性,所以种植后生长出来的头发仍保持了这一特性,不会再次脱落。且因毛囊来源于患者本身,所以新长出的头发 会与原有头发融为一体,自然、美观。而我院所拥有的lhs无痕植发技术更能做到手术:无痛、无痕、无痂,带给脱发患者好的植发效果。 头发种植真的能解决脱发问题吗？相信通过杭州杭城植发医院专家的介绍,您对头发种植应该有了更深的了解。正受脱发困扰的您何不相信科学,为未来的自己挑战一把,杭州杭城植发医院头发种植等着您。 杭城植发医院温馨提示: 杭州杭城植发医院专家指出:患有毛发问题不要轻视,要及时咨询医生并确定最佳的解决方案。如您还有更多疑问或是有来院的需求,可以通过以下方式与杭州杭城植发专家进行在线咨询！(如果您对来院路线不清楚,建议您用拍照方式保存或用小纸条记录收藏好,方便您更快来院诊疗,早日健康完美！
trainer_interface.cc(367) LOG(INFO) Reserved chars are found. Skipped: 杭州下城区治疗溢脂性脱发哪家医院好

**Comment by mikeda100** [comment]
And here are other occurrences that might be related to the above problem:

------------------

trainer_interface.cc(400) LOG(INFO) Adding meta_piece: <0xFE>
trainer_interface.cc(400) LOG(INFO) Adding meta_piece: <0xFF>
trainer_interface.cc(405) LOG(INFO) Normalizing sentences...
trainer_interface.cc(451) LOG(INFO) Found null character. The corpus must be encoded in utf-8.
trainer_interface.cc(466) LOG(INFO) all chars count=506400706
trainer_interface.cc(477) LOG(INFO) Done: 99.95% characters are covered.
trainer_interface.cc(487) LOG(INFO) Alphabet size=4941
trainer_interface.cc(488) LOG(INFO) Final character coverage=0.9995
trainer_interface.cc(520) LOG(INFO) Done! preprocessed 231706 sentences.
trainer_interface.cc(526) LOG(INFO) Tokenizing input sentences with whitespace: 231706

trainer_interface.cc(537) LOG(INFO) Done! 6407775
bpe_model_trainer.cc(167) LOG(INFO) Updating active symbols. max_freq=7377228 min_freq=80
bpe_model_trainer.cc(258) LOG(INFO) Added: freq=2256059 size=20 all=2000916 active=102323 piece=an
bpe_model_trainer.cc(258) LOG(INFO) Added: freq=1455330 size=40 all=2003535 active=104942 piece=▁and
bpe_model_trainer.cc(258) LOG(INFO) Added: freq=754963 size=60 all=2006664 active=108071 piece=▁g

**Comment by s-JoL** [comment]
I am replying to all three of your issues here. The maximum length I am using is 16384, but I feel that this parameter has little impact, as there will always be some very long texts that are difficult to avoid. Also, "Lots of skippings" is a normal phenomenon. In sentencepiece, "_" is used to replace spaces, and I suspect that there are special characters in some samples that conflict with reserved keywords "_". I have also encountered this during training without special handling.
