### ISSUE TITLE
有计划加入RedPajama-Data-1T相关数据训练模型吗？

### ISSUE THREAD

**Issue by mblank5** [s-JoL/Open-Llama#16]
[RedPajama-Data-1T](https://huggingface.co/datasets/togethercomputer/RedPajama-Data-1T) 宣称自己对标LLAMA的数据，应该是比pile要好不少的，有计划使用来训练及发布预训练好的checkpoint嘛

**Comment by s-JoL** [comment]
我最近也关注到了这个数据集，受资源限制使用这个数据集完整预训练会耗费太长时间，目前看意义不大。我下一步考虑的是基于llama的ckpt做继续中文的预训练，主要使用中文数据，会采样部分英文避免损失英文原本的能力
