### ISSUE TITLE
dataset download fail

### ISSUE THREAD

**Issue by leiwen83** [s-JoL/Open-Llama#20]
两个数据集下载都失败了。the pipe和wudao
update-alternatives: warning: skip creation of /usr/share/man/man1/unrar.1.gz because associated file /usr/share/man/man1/unrar-nonfree.1.gz (of link group unrar) doesn't exist
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

有hugging face的下载链接不？或者能否提供其他的下载链接？
感谢您的分享

**Comment by s-JoL** [comment]
the pile的就多下载几次就完整了，wudao需要自己申请一下，申请链接在readme里有
可参考 https://github.com/s-JoL/Open-Llama/issues/5
