### ISSUE TITLE
instruction tuning失败

### ISSUE THREAD

**Issue by leiwen83** [s-JoL/Open-Llama#21]
accelerate launch --config_file configs/default_config.yaml inctruction_tuning.py  

File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data/saved_ckpt/83200.pt'

83200.pt 这个checkpoint是需要经过预训练生成出来的吗？

**Comment by s-JoL** [comment]
哦对，是的。跟这个一样的 https://github.com/s-JoL/Open-Llama/issues/18 今天晚点我上传一下

**Comment by s-JoL** [comment]
从这里下载一下 https://huggingface.co/s-JoL/Open-Llama-V1-pretrain/tree/main
