### ISSUE TITLE
可以提供一个dockerfile吗？

### ISSUE THREAD

**Issue by leiwen83** [s-JoL/Open-Llama#24]
环境现在太多，有的时候设置有问题，可以提供一个验证过的dockerfile环境吗？
多谢~

**Comment by leiwen83** [comment]
请问这个有进展吗？

**Comment by s-JoL** [comment]
这方面我也没什么经验，我查了一下 感觉这个可以用
https://hub.docker.com/layers/pytorch/pytorch/1.13.1-cuda11.6-cudnn8-runtime/images/sha256-1e26efd426b0fecbfe7cf3d3ae5003fada6ac5a76eddc1e042857f5d049605ee?context=explore
，你可以试试

leiwen83 ***@***.***> 于2023年5月1日周一 19:32写道：

**Comment by leiwen83** [comment]
用这个dockerfile。安装requirement之后，有些问题：

# python3 utils/train_tokenizer.py
Traceback (most recent call last):
  File "/data/aigc/Open-Llama/utils/train_tokenizer.py", line 12, in <module>
    from dataset.data_iter import DataIter, create_shard_kwargs
ModuleNotFoundError: No module named 'dataset.data_iter'


# python3 utils/merge_tokenizer.py
Traceback (most recent call last):
  File "/data/aigc/Open-Llama/utils/merge_tokenizer.py", line 3, in <module>
    from sentencepiece import sentencepiece_model_pb2 as model
  File "/opt/conda/lib/python3.10/site-packages/sentencepiece/sentencepiece_model_pb2.py", line 34, in <module>
    _descriptor.EnumValueDescriptor(
  File "/opt/conda/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

**Comment by s-JoL** [comment]
我好像也遇到过，就降级protobuf就行

**Comment by leiwen83** [comment]
protobuf降到3.20.0以后，utils/merge_tokenizer.py可以运行，
不过dataset包仍然有问题，你那边dataset的版本是多少？

Traceback (most recent call last):
  File "/data/aigc/Open-Llama/utils/train_tokenizer.py", line 12, in <module>
    from dataset.data_iter import DataIter, create_shard_kwargs
ModuleNotFoundError: No module named 'dataset.data_iter'

**Comment by s-JoL** [comment]
> protobuf降到3.20.0以后，utils/merge_tokenizer.py可以运行， 不过dataset包仍然有问题，你那边dataset的版本是多少？
> 
> Traceback (most recent call last): File "/data/aigc/Open-Llama/utils/train_tokenizer.py", line 12, in from dataset.data_iter import DataIter, create_shard_kwargs ModuleNotFoundError: No module named 'dataset.data_iter'

抱歉，我看了一下这个错是因为改成v2的时候忘了适配训练分词的，我今天改一下，改完告诉你

**Comment by s-JoL** [comment]
已修复，更新一下train_tokenizer.py文件就行

**Comment by s-JoL** [comment]
话说你这个docker能用了可以提一个pull request啊

**Comment by leiwen83** [comment]
train_tokenizer.py可以运行了。
目前看起来这个pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime 直接用就可以。我这边再来看看后面跑起来后还要加什么，需要的话，我再提一个pull。
