### ISSUE TITLE
关于预训练中的eval阶段

### ISSUE THREAD

**Issue by xikaluo** [s-JoL/Open-Llama#27]
您好，关于预训练过程中的evaluate阶段的代码，我有三个问题希望能得到您的解答：

1. 预训练过程中的evaluate起到的作用是什么？我看您在pretrain_llama.py里的evaluate仅仅只是把输出结果通过wandb进行记录，似乎并没有涉及到计算准确率和进行early-stop。那是不是不加evaluate阶段也可以？

2. 想问一下如果不进行early-stop，是否会导致预训练阶段的过拟合？

3. 我在3090上尝试用您的pretrain代码预训练一个小模型，仅使用单卡时代码能够正常跑通，8卡运行时会在evaluate阶段的model.generate处卡住，想问一下这种会是由于什么原因导致的？
我所使用的模型参数为：
hidden_size = 1024
num_hidden_layers = 24
num_attention_heads = 16
intermediate_size = 2048
use_stable_embedding = False

希望能得到您的解答，十分感谢

**Comment by cxj01** [comment]
我想请教下这些参数是在哪边定义的？可以使得在3090上运行？

**Comment by xikaluo** [comment]
> 我想请教下这些参数是在哪边定义的？可以使得在3090上运行？

pretrain_llama.py里，raw_model = LlamaForCausalLM(LlamaConfig())这里进行定义

**Comment by s-JoL** [comment]
1. 是的，这里eval没什么作用，只是肉眼看一下模型预测结果怎么样，可以去掉。
2. 因为在预训练中数据量非常大，我目前设置的超参数甚至不能把全部数据过一遍，所以我认为过拟合应该没啥问题。如果你的数据比较少的话可以根据数据量调整config中的num_training_steps。
3. 对于多卡训练卡住我目前遇到的情况是：显卡利用率显示100%但是看显卡温度和功率都是没在运行的状态，如果你遇到的也是这样可能是多卡之前同步有问题，我之前发现在第0step做eval有时候会卡住，如果是训练了几十step再eval就没事了。所以你可以尝试在这里 https://github.com/s-JoL/Open-Llama/blob/main/pretrain_llama.py#L151 也加一个 and data_step > 0

**Comment by llllooong** [comment]
您好，我有两个问题
1. 如果数据全部都过很多遍，是不是pretrain阶段过拟合就可能会出现了，也就需要early-stop了？
2. 我看到instruction turning的eval和pretrain用的一样的eval方法，instruction turning的eval loss也没什么用，并且不需要early-stop吗？

**Comment by s-JoL** [comment]
1. 如果确实过了很多遍确实会出现过拟合，我理解设置总共的step做一定限制就可以
2. 在instruction tuning时那些eval就不再适用了，因为格式不一致强行用效果也不太好。训练的话根据我观察过三遍数据会比一遍要好，并且也没有出现很明显的过拟合，我猜测是instruction tuning还是一个比较难的任务，同时数据量也不少，估计训练更多epoch才会过拟合。

**Comment by xikaluo** [comment]
> 1. 是的，这里eval没什么作用，只是肉眼看一下模型预测结果怎么样，可以去掉。
> 2. 因为在预训练中数据量非常大，我目前设置的超参数甚至不能把全部数据过一遍，所以我认为过拟合应该没啥问题。如果你的数据比较少的话可以根据数据量调整config中的num_training_steps。
> 3. 对于多卡训练卡住我目前遇到的情况是：显卡利用率显示100%但是看显卡温度和功率都是没在运行的状态，如果你遇到的也是这样可能是多卡之前同步有问题，我之前发现在第0step做eval有时候会卡住，如果是训练了几十step再eval就没事了。所以你可以尝试在这里 https://github.com/s-JoL/Open-Llama/blob/main/pretrain_llama.py#L151 也加一个 and data_step > 0

感谢您的解答，我这边刚才把自己生成的config里的zero_stage从3改成2之后就不卡了，猜测可能还是deepspeed配置的问题？

**Comment by llllooong** [comment]
> 1. 如果确实过了很多遍确实会出现过拟合，我理解设置总共的step做一定限制就可以
> 2. 在instruction tuning时那些eval就不再适用了，因为格式不一致强行用效果也不太好。训练的话根据我观察过三遍数据会比一遍要好，并且也没有出现很明显的过拟合，我猜测是instruction tuning还是一个比较难的任务，同时数据量也不少，估计训练更多epoch才会过拟合。

哦哦～那在instruction eval的时候，我们如果正常划分一部分验证集，判断一下eval loss，是不是可能会好一些？

**Comment by s-JoL** [comment]
哦哦，原来你用的是stage3啊，那在做eval和保存ckpt的时候需要一些特殊处理，因为模型参数被分配到不同的device了，如果要使用的话可以参考这里修改 https://huggingface.co/docs/accelerate/usage_guides/deepspeed

**Comment by xikaluo** [comment]
> 哦哦，原来你用的是stage3啊，那在做eval和保存ckpt的时候需要一些特殊处理，因为模型参数被分配到不同的device了，如果要使用的话可以参考这里修改 https://huggingface.co/docs/accelerate/usage_guides/deepspeed 需要一个unwarp操作
> 
> ```
> unwrapped_model = accelerator.unwrap_model(model)
> ```

原来如此，十分感谢🙏

**Comment by s-JoL** [comment]
> > 1. 如果确实过了很多遍确实会出现过拟合，我理解设置总共的step做一定限制就可以
> > 2. 在instruction tuning时那些eval就不再适用了，因为格式不一致强行用效果也不太好。训练的话根据我观察过三遍数据会比一遍要好，并且也没有出现很明显的过拟合，我猜测是instruction tuning还是一个比较难的任务，同时数据量也不少，估计训练更多epoch才会过拟合。
> 
> 哦哦～那在instruction eval的时候，我们如果正常划分一部分验证集，判断一下eval loss，是不是可能会好一些？

确实，是一个好主意，这几天改一下
