### ISSUE TITLE
where is model implement？

### ISSUE THREAD

**Issue by wac81** [s-JoL/Open-Llama#32]
where is model implement？

how to modify model structure

**Comment by wac81** [comment]
https://github.com/huggingface/transformers/commit/e772218a4a4369494e7cefacc9530107840569a2#diff-416b67ecce893901858674f96df379b96918f04972f230ff70bc553a55847ce5

it's here?
not different from llama

**Comment by s-JoL** [comment]
The specific differences have been described in detail in the readme file.
