### ISSUE TITLE
what ‘s difference between 10w_vocab_wudao5_pile10.model and llama_tokenizer_extended.model

### ISSUE THREAD

**Issue by wac81** [s-JoL/Open-Llama#33]
what ‘s difference between 10w_vocab_wudao5_pile10.model and llama_tokenizer_extended.model

**Comment by s-JoL** [comment]
10w_vocab_wudao5_pile10.model is a tokenizer model trained on both Chinese
and English, while llama_tokenizer_extended.model is a tokenizer model
trained on Chinese only with 40,000 pieces and then merged with the llama
tokenizer.

**Comment by wac81** [comment]
i have question: whether to remove words that are too long tail?

**Comment by s-JoL** [comment]
There is no special treatment for long tail words.
