### ISSUE TITLE
instruct finetune报错，初始化的模型和加载的83200.pt好像结构上对不齐

### ISSUE THREAD

**Issue by lierer007** [s-JoL/Open-Llama#37]
RuntimeError: Error(s) in loading state_dict for OpenLlamaForCausalLM:
        Missing key(s) in state_dict: "lm_head.weight". 
        Unexpected key(s) in state_dict: "model.embed_layer_norm.weight", "model.embed_layer_norm.bias".

**Comment by s-JoL** [comment]
现在config里对应的是原始的llama模型，使用83200.pt需要把use_stable_embedding和shared_input_output_embedding设成True

**Comment by lierer007** [comment]
您的xformers是啥版本哈，用现在的requirements.txt安装，xformers的版本和pytorch的版本好像对不上；导致总是有些算子找不着

**Comment by s-JoL** [comment]
我用的0.0.16
