### ISSUE TITLE
Is zero2&zero3 with cpuoffload tested?

### ISSUE THREAD

**Issue by lipiji** [s-JoL/Open-Llama#38]
I am wondering the performance but I have no gpu resource to test it.

**Comment by s-JoL** [comment]
Thank you for your interest in our project. Currently, we have tested stage2/stage3 and offload on a single machine with 8 GPUs. For stage3, we need to make some modifications to the current evaluation process, but other than that, everything can be run directly. Relevant discussions can be found in https://github.com/s-JoL/Open-Llama/issues/22. The performance of these situations on multiple machines is currently being tested and will be added to the README once the testing is complete.

**Comment by s-JoL** [comment]
The training of 65B models is now supported and the specific training speed and configuration used have been updated in the Updates section of the readme.
