### ISSUE TITLE
支持基于 llama-7b权重做二次增量预训练吗？

### ISSUE THREAD

**Issue by baketbek** [s-JoL/Open-Llama#4]
请问支持基于 llama-7b权重做二次增量预训练吗？支持的话，有相关步骤吗

**Comment by Bayes-Song** [comment]
感谢对本项目的关注，我今天会尝试一下这个方案

**Comment by baketbek** [comment]
太棒了，大佬能加你微信吗 或者有微信沟通群之类的吗？感谢感谢

**Comment by Vincent131499** [comment]
这个有结果了吗

**Comment by s-JoL** [comment]
参考这个[issue](https://github.com/s-JoL/Open-Llama/issues/10)中的内容，可以使用pyllama下载7B模型继续训练

**Comment by s-JoL** [comment]
基于llama-7B进行继续预训练代码已合并到main分支
