### ISSUE TITLE
关于83200.pt？

### ISSUE THREAD

**Issue by ScottishFold007** [s-JoL/Open-Llama#41]
请问，您这个预训练的模型[83200.pt](https://huggingface.co/s-JoL/Open-Llama-V1-pretrain/blob/main/83200.pt)，是指跑了83200step吗？[Open-Llama-V1](https://huggingface.co/s-JoL/Open-Llama-V1)是基于这个训练的吗？

**Comment by s-JoL** [comment]
global step是83200，同时还有12的梯度累计，所以算data step差不多1M。是基于这个训练的。

**Comment by s-JoL** [comment]
呃，这是step，token数在readme写了，300B

**Comment by ScottishFold007** [comment]
> 呃，这是step，token数在readme写了，300B

抱歉，刚看到了，谢谢细心解答！
