### ISSUE TITLE
Released model on demo

### ISSUE THREAD

**Issue by Manuel030** [s-JoL/Open-Llama#45]
Hi there,

thank you for your work! I see some performance divergence between your online demo and my local model instance. Are those the same (Open-Llama-V1)?

**Comment by s-JoL** [comment]
Wow, you've got some sharp observation skills! You're right, at the moment, they're not the same model. The one in the online demo is the model I optimized after pre-training and added more instruct-tuning data to. I'm currently testing it out on this deployment, and I'm planning to upload it to Hugging Face within the next couple of days. I'm curious, how did you notice the performance difference between the two models? And in which areas do you think they differ the most? Your answer will be really helpful for my iteration process, so thanks in advance!

**Comment by Manuel030** [comment]
I have a couple of test cases I have tried in the Demo first and the results were much better than what I've got from the V1 model. The domain is having an empathetic dialog with the system in English. 

Looking forward to the new release!

**Comment by Manuel030** [comment]
Which instruct datasets did you use to further finetune?

**Comment by s-JoL** [comment]
In the instruct-tuning phase, I mainly added the following data sets, but they are not mainly for English dialogue tasks, so I speculate that the improvement may come from a better pretrained model.

dataset_map = {
    "BelleGroup/train_2M_CN": "belle_2M",
    "qwedsacf/grade-school-math-instructions": "grade_school_math",
    "camel-ai/math": "camel_ai_math",
    "camel-ai/physics": "camel_ai_physics",
    "camel-ai/chemistry": "camel_ai_chemistry",
    "camel-ai/biology": "camel_ai_biology",
    ("bigscience/xP3mt", "code"): "xP3mt_code",
    ("bigscience/xP3mt", "zh"): "xP3mt_zh",
}

**Comment by johnny0213** [comment]
Look forward to your updates. The preformance of your web demo is very promising. So I can't wait to try it out on my local machine with vertical data.

**Comment by s-JoL** [comment]
> Look forward to your updates. The preformance of your web demo is very promising. So I can't wait to try it out on my local machine with vertical data.

We have released the model used in the web demo, the link to the new model have been updated in the readme.
