### ISSUE TITLE
33B和65B模型训练

### ISSUE THREAD

**Issue by Stick-To** [s-JoL/Open-Llama#46]
作者大大
我的机器配置是8x80G A100, 内存512G
启动33b模型使用命令
```accelerate  launch  --main_process_port  30001 --config_file  configs/accelerate_configs/ds_stage3.yaml train_lm.py --train_config configs/pretrain_config.yaml --model_config configs/model_configs/33B.json``` 会oom
```torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.83 GiB (GPU 3; 79.20 GiB total capacity; 67.98 GiB already allocated; 1.75 GiB free; 76.03 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CON```
启动65b模型
```accelerate  launch  --main_process_port  30001 --config_file  configs/accelerate_configs/ds_stage3_offload.yaml train_lm.py --train_config configs/pretrain_config.yaml --model_config configs/model_configs/65B.json ```
会内存爆炸卡死

**Comment by s-JoL** [comment]
相关数据我是在64cpu, 1T memory的机器上测试的。稍晚我换成和你一样的配置再试试。

**Comment by s-JoL** [comment]
我在512G内存的机器上复现了你说的问题，我再研究一下，可能是我之前看的监控不太准。

**Comment by Stick-To** [comment]
@s-JoL  你之前跑33b用的是什么配置啊？ 33b模型我看readme没有 cpu offload， 又能在512G机器上跑通的命令吗

**Comment by s-JoL** [comment]
目前看33B模型在512G内存上把batch size改成1就可以跑，但是用free -h看占用内存又很少，你也可以试试

**Comment by Stick-To** [comment]
@s-JoL  cpu offload了吗

**Comment by s-JoL** [comment]
> @s-JoL cpu offload了吗

没有用到offload，只使用stage3就行，offload还挺占内存的。

**Comment by s-JoL** [comment]
我这里测试使用的都是48卡，我试了一下使用单卡确实跑不了65B模型。
