### ISSUE TITLE
train_lm.py一直waiting是为什么？

### ISSUE THREAD

**Issue by leiwen83** [s-JoL/Open-Llama#47]
我现在开始用stage3来train，不过刚开始就卡住，看显存和内存，不像是不够的样子。这是为什么呢？
accelerate launch --config_file configs/accelerate_configs/ds_stage3_offload.yaml train_lm.py --train_config configs/pretrain_config.yaml --model_config configs/model_configs/7B.json

I0510 07:28:04.417845 139863945226048 distributed_c10d.py:337] Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:2 (world_size=8, worker_count=7, timeout=0:30:00)
I0510 07:28:04.428285 140051304576832 distributed_c10d.py:337] Waiting in store based barrier to initialize process group for rank: 7, key: store_based_barrier_key:2 (world_size=8, worker_count=7, timeout=0:30:00)

**Comment by s-JoL** [comment]
https://discuss.pytorch.org/t/pytorch-hangs-after-got-error-during-ddp-training/127326
https://github.com/NVIDIA/NeMo/issues/4418
看起来是ddp本身的问题，你参考这些试试呢

**Comment by leiwen83** [comment]
是wandb的问题，我禁掉就可以继续了
export WANDB_DISABLED=true
