### ISSUE TITLE
关于V2版代码数据处理的两个问题

### ISSUE THREAD

**Issue by xikaluo** [s-JoL/Open-Llama#51]
您好，我在使用您的V2版本代码时，遇到如下两个问题，应该是数据处理过程中存在一些没有处理的异常情况：

问题1:
pretrain_transform函数batch["text"] = [batch["title"][0] + "\n" + batch["content"][0]]报错：
TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'str'
可能的出错原因：
load_dataset加载数据集时并没有把所有的数据都转成str格式
解决方法：改成batch["text"] = [str(batch["title"][0]) + "\n" + str(batch["content"][0])]后，暂时未遇到类似的问题

问题2:
遍历dataloader时，dataloader._process_data(data)报错，最终定位到torch/utils/data/_utils/collate.py128行，
`return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})`
报错KeyError: 'id'
可能的出错原因：
您的v2版代码里，pretrain_transform返回的是字典，而非像v1版一样返回tokenize结果，因此wudao和pile数据返回的key不一致，导致出错。
解决方法：
可能需要修改一下preprocess_the_pile和preprocess_wudao的代码？在数据预处理的时候就将两份数据的key进行对齐

**Comment by s-JoL** [comment]
这个错误我目前没有遇到过，第一个错误看起来是title没有被当作字符串而是被转成了datetime，而第二个错误感觉也不应该出现https://github.com/s-JoL/Open-Llama/blob/main/dataset/dataset.py#L240 可以看这里，选择了返回的字典只保留input ids，其他key应该会被抛弃。

因为中间换过一次数据下载链接会不会下载的wudao数据集有变化？请问你方便提供一些数据集的sample我们一起看看么？
