### ISSUE TITLE
v2的checkpoint好像是pretrain模型，不是instruct tuning后的模型

### ISSUE THREAD

**Issue by Expert68** [s-JoL/Open-Llama#53]
https://huggingface.co/s-JoL/Open-Llama-V2，我使用了v2的checkpoint，回复如下所示，传上来的应该是预训练模型，麻烦作者大大更新一下模型。
![image](https://github.com/s-JoL/Open-Llama/assets/39072886/03d8d3f3-c4f0-4402-a5ed-25eb767cce8c)

**Comment by ouwenjie03** [comment]
把那个inputs的最后一个token</s>去掉就好了

**Comment by honglianglv** [comment]
> [https://huggingface.co/s-JoL/Open-Llama-V2-pretrain/tree/main，我使用了v2的checkpoint，回复如下所示，传上来的应该是预训练模型，麻烦作者大大更新一下模型。](https://huggingface.co/s-JoL/Open-Llama-V2-pretrain/tree/main%EF%BC%8C%E6%88%91%E4%BD%BF%E7%94%A8%E4%BA%86v2%E7%9A%84checkpoint%EF%BC%8C%E5%9B%9E%E5%A4%8D%E5%A6%82%E4%B8%8B%E6%89%80%E7%A4%BA%EF%BC%8C%E4%BC%A0%E4%B8%8A%E6%9D%A5%E7%9A%84%E5%BA%94%E8%AF%A5%E6%98%AF%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%EF%BC%8C%E9%BA%BB%E7%83%A6%E4%BD%9C%E8%80%85%E5%A4%A7%E5%A4%A7%E6%9B%B4%E6%96%B0%E4%B8%80%E4%B8%8B%E6%A8%A1%E5%9E%8B%E3%80%82) ![image](https://user-images.githubusercontent.com/39072886/237954269-03d8d3f3-c4f0-4402-a5ed-25eb767cce8c.png)

指令微调之后的模型也更新了，在这里：https://huggingface.co/s-JoL/Open-Llama-V2

**Comment by Expert68** [comment]
> > [https://huggingface.co/s-JoL/Open-Llama-V2-pretrain/tree/main，我使用了v2的checkpoint，回复如下所示，传上来的应该是预训练模型，麻烦作者大大更新一下模型。](https://huggingface.co/s-JoL/Open-Llama-V2-pretrain/tree/main%EF%BC%8C%E6%88%91%E4%BD%BF%E7%94%A8%E4%BA%86v2%E7%9A%84checkpoint%EF%BC%8C%E5%9B%9E%E5%A4%8D%E5%A6%82%E4%B8%8B%E6%89%80%E7%A4%BA%EF%BC%8C%E4%BC%A0%E4%B8%8A%E6%9D%A5%E7%9A%84%E5%BA%94%E8%AF%A5%E6%98%AF%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%EF%BC%8C%E9%BA%BB%E7%83%A6%E4%BD%9C%E8%80%85%E5%A4%A7%E5%A4%A7%E6%9B%B4%E6%96%B0%E4%B8%80%E4%B8%8B%E6%A8%A1%E5%9E%8B%E3%80%82) ![image](https://user-images.githubusercontent.com/39072886/237954269-03d8d3f3-c4f0-4402-a5ed-25eb767cce8c.png)
> 
> 指令微调之后的模型也更新了，在这里：https://huggingface.co/s-JoL/Open-Llama-V2



> > [https://huggingface.co/s-JoL/Open-Llama-V2-pretrain/tree/main，我使用了v2的checkpoint，回复如下所示，传上来的应该是预训练模型，麻烦作者大大更新一下模型。](https://huggingface.co/s-JoL/Open-Llama-V2-pretrain/tree/main%EF%BC%8C%E6%88%91%E4%BD%BF%E7%94%A8%E4%BA%86v2%E7%9A%84checkpoint%EF%BC%8C%E5%9B%9E%E5%A4%8D%E5%A6%82%E4%B8%8B%E6%89%80%E7%A4%BA%EF%BC%8C%E4%BC%A0%E4%B8%8A%E6%9D%A5%E7%9A%84%E5%BA%94%E8%AF%A5%E6%98%AF%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%EF%BC%8C%E9%BA%BB%E7%83%A6%E4%BD%9C%E8%80%85%E5%A4%A7%E5%A4%A7%E6%9B%B4%E6%96%B0%E4%B8%80%E4%B8%8B%E6%A8%A1%E5%9E%8B%E3%80%82) ![image](https://user-images.githubusercontent.com/39072886/237954269-03d8d3f3-c4f0-4402-a5ed-25eb767cce8c.png)
> 
> 指令微调之后的模型也更新了，在这里：https://huggingface.co/s-JoL/Open-Llama-V2

@honglianglv 我问题写错了，我用的就是指令微调的模型

**Comment by honglianglv** [comment]
> 
你可以贴一下完整的代码，我直接使用的chat_server.py搭建的demo，效果比v1好了很多

![企业微信截图_fbb975f2-0171-4ada-88c5-88e3464775eb](https://github.com/s-JoL/Open-Llama/assets/751453/4974c98d-941e-443b-933c-d4f951fd6c51)
![企业微信截图_5cf17782-65fa-4835-8232-5b1d163ad059](https://github.com/s-JoL/Open-Llama/assets/751453/13d56cf4-5c6e-4ac9-964e-3241a23c7470)
![企业微信截图_99795e9f-64db-496d-8212-0b81085ebcac](https://github.com/s-JoL/Open-Llama/assets/751453/1c7667ad-15b8-414d-bba3-6d5003042425)

**Comment by honglianglv** [comment]
> 

你看看是不是作者之前提到的问题：https://github.com/s-JoL/Open-Llama/issues/49#issuecomment-1545285317 最好能贴出完整代码
 “我遇到过类似的情况，看一下调用tokenizer时是否加了add_special_tokens=False，如果没加的话他会自动在你输入的最后加一个eos记号，后面的内容就相当于下一句了，这时候模型会自己随便续写一些内容，跟问题完全无关。”

**Comment by s-JoL** [comment]
正如楼上几位所说，应该是调用方法变化导致最后错误的加了一个eos token

**Comment by Expert68** [comment]
@honglianglv @ouwenjie03 @s-JoL 感谢各位大大，确实ok了，多谢
