### ISSUE TITLE
基于v2的预训练模型进行指令微调时，LOSS总是忽大忽小，波动范围较大，不知道是否是正常情况？

### ISSUE THREAD

**Issue by honglianglv** [s-JoL/Open-Llama#54]
低的时候有0.8，高的时候有2.3，不知道大家训练的时候是不是也是这种情况？是因为训练还不充分的缘故吗？（目前训练了大概2个小时，总共5G的指令微调数据）

[2023-05-12 20:30:13,489] [INFO] [torch_checkpoint_engine.py:33:commit] [Torch] Checkpoint pytorch_model is ready now!
I0512 20:30:13.490093 140284242999104 logging.py:47] DeepSpeed Model and Optimizer saved to output dir data/saved_ckpt/7B_instruction/pytorch_model
I0512 20:30:13.491180 140284242999104 logging.py:47] Scheduler state saved in data/saved_ckpt/7B_instruction/scheduler.bin
I0512 20:30:13.492729 140284242999104 logging.py:47] Random states saved in data/saved_ckpt/7B_instruction/random_states_0.pkl
Epoch: 0, Global Step: 3051, Data Step: 3050, Loss: 0.8125, Token per second per gpu: 564.6297147981206
Epoch: 0, Global Step: 3101, Data Step: 3100, Loss: 2.03125, Token per second per gpu: 2999.5104936194425
Epoch: 0, Global Step: 3151, Data Step: 3150, Loss: 2.078125, Token per second per gpu: 2999.4936411123576
Epoch: 0, Global Step: 3201, Data Step: 3200, Loss: 2.15625, Token per second per gpu: 2997.8913711548653
Epoch: 0, Global Step: 3251, Data Step: 3250, Loss: 2.203125, Token per second per gpu: 2999.0908188699273
Epoch: 0, Global Step: 3301, Data Step: 3300, Loss: 1.125, Token per second per gpu: 3000.028080336949
Epoch: 0, Global Step: 3351, Data Step: 3350, Loss: 1.8984375, Token per second per gpu: 2998.797114319698
Epoch: 0, Global Step: 3401, Data Step: 3400, Loss: 1.796875, Token per second per gpu: 2997.457181530268
Epoch: 0, Global Step: 3451, Data Step: 3450, Loss: 0.439453125, Token per second per gpu: 2997.4025205262483
Epoch: 0, Global Step: 3501, Data Step: 3500, Loss: 2.15625, Token per second per gpu: 2997.202249851822
Epoch: 0, Global Step: 3551, Data Step: 3550, Loss: 0.9765625, Token per second per gpu: 2996.3489861889375
Epoch: 0, Global Step: 3601, Data Step: 3600, Loss: 1.8515625, Token per second per gpu: 2998.468727956593
Epoch: 0, Global Step: 3651, Data Step: 3650, Loss: 1.4375, Token per second per gpu: 2997.1825473994422
Epoch: 0, Global Step: 3701, Data Step: 3700, Loss: 1.3671875, Token per second per gpu: 2997.2918867307167
Epoch: 0, Global Step: 3751, Data Step: 3750, Loss: 1.1015625, Token per second per gpu: 2998.0614931246614
Epoch: 0, Global Step: 3801, Data Step: 3800, Loss: 2.359375, Token per second per gpu: 2997.3599415502686

**Comment by s-JoL** [comment]
![B2467C2D-E95A-4818-B2A9-6E550073D450](https://github.com/s-JoL/Open-Llama/assets/16948304/a1a619fc-7674-43d2-8013-7f6e5b3ea61f)
我这里训练时也会比较波动 多个epoch才会有稳定的下降

**Comment by honglianglv** [comment]
多谢回复，训练时间长一些确实loss在缓慢下降了。
![W B Chart 2023_5_13 10_52_35](https://github.com/s-JoL/Open-Llama/assets/751453/d0002187-cb08-470e-92f6-19d6051d2ef7)

**Comment by FrankWhh** [comment]
> ![B2467C2D-E95A-4818-B2A9-6E550073D450](https://user-images.githubusercontent.com/16948304/238105882-a1a619fc-7674-43d2-8013-7f6e5b3ea61f.jpeg) 我这里训练时也会比较波动 多个epoch才会有稳定的下降

这里是训练了几个epoch？怎么跟readme里的图不一样
