### ISSUE TITLE
Can this train regular llama models or just openllama?

### ISSUE THREAD

**Issue by teknium1** [s-JoL/Open-Llama#55]
Question in title ^

**Comment by s-JoL** [comment]
In fact, this project does not aim to propose a new model, but mainly to provide an open source implementation for llama, which has a relatively good effect at present. 
So the answer is yes, this project can train the original llama model, and the config example given now is the original llama model.

**Comment by teknium1** [comment]
> In fact, this project does not aim to propose a new model, but mainly to provide an open source implementation for llama, which has a relatively good effect at present. So the answer is yes, this project can train the original llama model, and the config example given now is the original llama model.

Do you know if it can train any HF model?
