### ISSUE TITLE
继续预训练的问题

### ISSUE THREAD

**Issue by HunterKruger** [s-JoL/Open-Llama#59]
由于新版代码用了huggingface dataset api，有没有办法监控每次run被用过的zst文件？这样的话在继续预训练的时候才有办法跳过这些文件

**Comment by s-JoL** [comment]
我也有类似的想法，在datasets里提出了一个issue，不过目前看还没人在做 https://github.com/huggingface/datasets/issues/5806

**Comment by HunterKruger** [comment]
好的，非常感谢
