### ISSUE TITLE
RLHF

### ISSUE THREAD

**Issue by XiaoYee** [s-JoL/Open-Llama#6]
感谢作者的开源，请问RLHF有计划嘛？大概什么时候能开源相关代码

**Comment by s-JoL** [comment]
感谢关注，目前没有找到一个中文较好的rlhf数据集，正在考虑使用gpt3.5把Anthropic/hh-rlhf翻译一部分做个能训练的demo。

**Comment by XiaoYee** [comment]
谢谢，希望能看到第一个在中文上有效果的开源RLHF实现。
