### ISSUE TITLE
Model Checkpoint + Adapter fine-tune?

### ISSUE THREAD

**Issue by bluecoconut** [s-JoL/Open-Llama#8]
This is sort of 2 questions:

Are the weights available anywhere, do you intend to make them available anywhere soon? (eg. on huggingface?)

Second: is it possible to introduce some recent fine-tuning work to this? (eg. specifically https://github.com/ZrrSkywalker/LLaMA-Adapter would be really great) 

Personal Interest: I'd love to be able to have an easy to use starting place to get weights + apply custom fine-tuning with multi-modal inputs

**Comment by s-JoL** [comment]
Regarding your first point, that is exactly what I have been focusing on lately. I plan to add a new model to the transformers library and upload the corresponding checkpoint this week. However, it may take some time to merge it into the master branch, so a non-master branch of the transformers library may be needed in the meantime.
As for the second point, I will need to read through the library you provided, but it doesn't look too complicated.
Lastly, multimodality is also an area of great interest to me, and I have been researching some related datasets recently.

**Comment by s-JoL** [comment]
The checkpoint after Instruct-tuning has been open-sourced on [HuggingFace](https://huggingface.co/s-JoL/Open-Llama-V1).
To use the checkpoint, you need to first install the latest version of Transformers using the following command.
``` base
pip install git+https://github.com/s-JoL/transformers.git@dev
```
